### ISSUE TITLE
download_zip_url won't accept cloud_name

### ISSUE THREAD

**Issue by mattiasarro** [cloudinary/pycloudinary#130]
When running 

```
cloudinary.utils.download_zip_url(
        public_ids=urls,
        resource_type='image',
        api_key="KEY",
        api_secret="SECRET",
        cloud_name="CLOUD_NAME"
    )
```

I get the error:

```
Traceback (most recent call last):
  File "download_images.py", line 107, in <module>
    download(query, args.batch_size)
  File "download_images.py", line 93, in download
    download_batch(curr_batch)
  File "download_images.py", line 71, in download_batch
    cloud_name=c.cloudinary_cloud_name,
  File "/Users/m/code/3rd/conda/envs/p3gpu/lib/python3.6/site-packages/cloudinary/utils.py", line 530, in download_zip_url
    return download_archive_url(**new_options)
  File "/Users/m/code/3rd/conda/envs/p3gpu/lib/python3.6/site-packages/cloudinary/utils.py", line 523, in download_archive_url
    return cloudinary_api_url("generate_archive") + "?" + urlencode(bracketize_seq(cloudinary_params), True)
  File "/Users/m/code/3rd/conda/envs/p3gpu/lib/python3.6/site-packages/cloudinary/utils.py", line 459, in cloudinary_api_url
    if not cloud_name: raise ValueError("Must supply cloud_name")
ValueError: Must supply cloud_name
```

I have made the following workaround that fixes it:

```
› git diff
diff --git a/cloudinary/utils.py b/cloudinary/utils.py
index df1f3ae..5893637 100644
--- a/cloudinary/utils.py
+++ b/cloudinary/utils.py
@@ -518,7 +518,8 @@ def download_archive_url(**options):
     params = options.copy()
     params.update(mode="download")
     cloudinary_params = sign_request(archive_params(**params), options)
-    return cloudinary_api_url("generate_archive") + "?" + urlencode(bracketize_seq(cloudinary_params), True)
+    url_base = cloudinary_api_url("generate_archive", cloud_name=options.get("cloud_name"))
+    return url_base + "?" + urlencode(bracketize_seq(cloudinary_params), True)
```

Am I missing something or this was a bug?

**Comment by idobarnoam** [comment]
Thank for pointing this out @mattiasarro 

Let us check this internally and see how to handle this.

**Comment by idobarnoam** [comment]
Hi @mattiasarro, 

Just letting you know we've integrated a fix to this.
