### ISSUE TITLE
Empty file error when uploading

### ISSUE THREAD

**Issue by MaximLippeveld** [cloudinary/pycloudinary#235]
Hi,

I get the following error when a file is uploaded in an AdminForm.

```
Environment:


Request Method: POST
Request URL: https://hi.maximl.be/admin/cookbook/recipe/add/

Django Version: 3.0.4
Python Version: 3.7.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'cookbook',
 'bootstrap4',
 'fontawesome_5',
 'ckeditor',
 'easy_thumbnails',
 'image_cropping']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1638, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1565, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1081, in save_model
    obj.save()
  File "./cookbook/models.py", line 47, in save
    super(Recipe, self).save(*args, **kwargs)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/db/models/base.py", line 746, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/db/models/base.py", line 784, in save_base
    force_update, using, update_fields,
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/db/models/base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/db/models/base.py", line 926, in _do_insert
    using=using, raw=raw,
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1390, in execute_sql
    for sql, params in self.as_sql():
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1335, in as_sql
    for obj in self.query.objs
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1335, in <listcomp>
    for obj in self.query.objs
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1334, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1285, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/cloudinary/models.py", line 110, in pre_save
    instance_value = uploader.upload_resource(value, **options)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/cloudinary/uploader.py", line 61, in upload_resource
    result = upload(file, **options)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/cloudinary/uploader.py", line 46, in upload
    return call_cacheable_api("upload", params, file=file, **options)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/cloudinary/uploader.py", line 341, in call_cacheable_api
    result = call_api(action, params, http_headers, return_error, unsigned, file, timeout, **options)
  File "/home/pi/kitkookt/venv/lib/python3.7/site-packages/cloudinary/uploader.py", line 421, in call_api
    raise Error(result["error"]["message"])

Exception Type: Error at /admin/cookbook/recipe/add/
Exception Value: Empty file
```

I have solved the issue by adding `file.seek(0)` in uploader.py since the file descriptor was at the end of the file when the data to be uploaded was read.

**Comment by shirlymanor** [comment]
Thank you for the feedback. We are checking it with the team.

**Comment by surasshu0x0** [comment]
i was getting the same error message when writing tests for my api, i had to call `file_object.seek(0)` anytime i wanted to pass it to cloudinary, that worked.

**Comment by victorli-cloudinary** [comment]
@MaximLippeveld Hi there, thank you for providing this feedback originally. Just an update that in June 2020 we issued a fix for this to seek to 0 by default.
