### ISSUE TITLE
Error while testing

### ISSUE THREAD

**Issue by hsk20011** [cloudinary/pycloudinary#347]
import cloudinary
from cloudinary.uploader import upload
from cloudinary.utils import cloudinary_url

# Config
cloudinary.config(
  cloud_name = "***",
  api_key = "***",
  api_secret = "***",
  secure = True
)

# Upload
upload("https://upload.wikimedia.org/wikipedia/commons/a/ae/Olympic_flag.jpg", public_id="olympic_flag")

==================================================================================

python cloudinaryTst.py
Traceback (most recent call last):
  File "C:\WPy64-31050\YHB\cloudinaryTst.py", line 21, in <module>
    upload("https://upload.wikimedia.org/wikipedia/commons/a/ae/Olympic_flag.jpg")
  File "C:\WPy64-31050\YHB\venv\lib\site-packages\cloudinary-1.32.0-py3.10.egg\cloudinary\uploader.py", line 50, in upload
    return call_cacheable_api("upload", params, file=file, **options)
  File "C:\WPy64-31050\YHB\venv\lib\site-packages\cloudinary-1.32.0-py3.10.egg\cloudinary\uploader.py", line 467, in call_cacheable_api
    result = call_api(action, params, http_headers, return_error, unsigned, file, timeout, **options)
  File "C:\WPy64-31050\YHB\venv\lib\site-packages\cloudinary-1.32.0-py3.10.egg\cloudinary\uploader.py", line 539, in call_api
    response = _http.request("POST", api_url, param_list, headers, **kw)
  File "C:\WPy64-31050\YHB\venv\lib\site-packages\urllib3\_request_methods.py", line 118, in request
    return self.request_encode_body(
  File "C:\WPy64-31050\YHB\venv\lib\site-packages\urllib3\_request_methods.py", line 198, in request_encode_body
    raise TypeError(
TypeError: request got values for both 'fields' and 'body', can only specify one.

**Comment by MSutt** [comment]
I think this error happens when having urllib3 package version that does not match `"urllib3>=1.26.5,<2"` as defined in [setup.py](https://github.com/cloudinary/pycloudinary/blob/4f1230c32dbae13ba74016d3a90f2146095b6f0c/setup.py#LL63C11-L63C32)

**Comment by tommyg-cld** [comment]
thx @MSutt , @hsk20011 can you please update your urllib3 package to be >= 1.26.5 and let me know if the test still fails?
