### ISSUE TITLE
 cloudinary.api.resources_by_asset_folder Error

### ISSUE THREAD

**Issue by hsk20011** [cloudinary/pycloudinary#349]
res = cloudinary.api.resources_by_asset_folder('prd', tags = True, metadata = True)
        print('res=', res)
        return res['resources']

Traceback (most recent call last):
  File "C:\WPy64-31050\YHB\venv\lib\site-packages\cloudinary-1.32.0-py3.10.egg\cloudinary\api_client\execute_request.py", line 76, in execute_request
    result = json.loads(body.decode('utf-8'))
  File "C:\WPy64-31050\python-3.10.5.amd64\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\WPy64-31050\python-3.10.5.amd64\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\WPy64-31050\python-3.10.5.amd64\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

**Comment by atdcloud** [comment]
method resources_by_asset_folder currently not implemented in python sdk.
